---
settings:
  secret: 12345
  db:
    blog:
      db: blog
      addr: 100.97.108.34:27018
      user: laisky
      pwd: 1234
    twitter:
      db: twitter
      addr: 100.97.108.34:27018
      user: laisky
      pwd: 1234
    monitor:
      db: monitor
      addr: 100.97.108.34:27018
      user: laisky
      pwd: 1234
    mcp:
      db: mcp
      addr: 127.0.0.1
      user: postgres
      pwd: changeme
  web:
    url_prefix: /mcp           # internal mount path on the Go server
    public_url_prefix: /       # set to '/' to hide the prefix in generated links
  websearch:
    max_retry: 3          # default: 3
    engines:
      google:
        enabled: true     # default: false
        priority: 1       # lower numbers indicate higher priority; default is 1
        api_key: YOUR_GOOGLE_API_KEY
        cx: YOUR_PROGRAMMABLE_SEARCH_ENGINE_ID
      serp_google:
        enabled: true
        priority: 2
        api_key: YOUR_SERP_API_KEY
