---
settings:
  secret: 12345
  db:
    blog:
      db: blog
      addr: 100.97.108.34:27018
      user: laisky
      pwd: 1234
    twitter:
      db: twitter
      addr: 100.97.108.34:27018
      user: laisky
      pwd: 1234
    monitor:
      db: monitor
      addr: 100.97.108.34:27018
      user: laisky
      pwd: 1234
    mcp:
      db: mcp
      addr: 127.0.0.1
      user: postgres
      pwd: changeme
